# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

require 'pry'

User.destroy_all
Quest.destroy_all

marnie = User.create!(username: 'marnie', role: 'dm', profile: 'I am one of the founding DMs', purse: 500, email: 'marnie@gmail.com', password: 'testing', level: '33', abilities: 'Fire Blast, Ice Barrier, Cone of Cold', character_class: 'Mage', stats: {'str' => 4, 'dex' => 2, 'int' => 10})
david = User.create!(username: 'david', role: 'dm', profile: 'I am one of the founding DMs', purse: 500, email: 'david@gmail.com', password: 'testing', level: '33', abilities: 'Sinister Strike, Vanish, Gouge', character_class: 'Rogue', stats: {'str' => 10, 'dex' => 20, 'int' => 8})
brian = User.create!(username: 'brian', role: 'dm', profile: 'I am one of the founding DMs', purse: 500, email: 'brian@gmail.com', password: 'testing', level: '33', abilities: 'Immolate, Shadowbolt, Curse of Agony', character_class: 'Warlock', stats: {'str' => 10, 'dex' => 5, 'int' => 16})
hieu = User.create!(username: 'hieu', role: 'dm', profile: 'I am one of the founding DMs', purse: 500, email: 'hieu@gmail.com', password: 'testing', level: '33', abilities: 'Arcane Shot, Serpents Sting, Scattershot', character_class: 'Hunter', stats: {'str' => 10, 'dex' => 20, 'int' => 15})

bravewarrior = User.create!(username: 'bravewarrior', role: 'adventurer', profile: 'I am a brave warrior seeking new adventures!', purse: 1200, email: 'bravewarrior@gmail.com', password: 'testing', level: 25, abilities: 'Sword Slash, Shield Bash, Whirlwind Strike', character_class: 'Barbarian', stats: {'str' => 35, 'dex' => 20, 'int' => 8})
mysteriousmage = User.create!(username: 'mysteriousmage', role: 'adventurer', profile: 'I am a mysterious mage wielding powerful arcane magic!', purse: 800, email: 'mysteriousmage@gmail.com', password: 'testing', level: 18, abilities: 'Fireball, Frost Nova, Arcane Missile', character_class: 'Mage', stats: {'str' => 10, 'dex' => 15, 'int' => 40})
skilledhunter = User.create!(username: 'skilledhunter', role: 'adventurer', profile: 'I am a skilled hunter, tracking my prey across the lands!', purse: 600, email: 'skilledhunter@gmail.com', password: 'testing', level: 15, abilities: 'Aimed Shot, Multi-Shot, Steady Shot', character_class: 'Hunter', stats: {'str' => 25, 'dex' => 35, 'int' => 12})
cunningrogue = User.create!(username: 'cunningrogue', role: 'adventurer', profile: 'I am a cunning rogue, striking from the shadows!', purse: 1000, email: 'cunningrogue@gmail.com', password: 'testing', level: 22, abilities: 'Backstab, Stealth, Eviscerate', character_class: 'Rogue', stats: {'str' => 18, 'dex' => 40, 'int' => 15})
devotedcleric = User.create!(username: 'devotedcleric', role: 'adventurer', profile: 'I am a devoted cleric, healing the wounded and aiding my allies!', purse: 1400, email: 'adventurer5@example.com', password: 'testing', level: 30, abilities: 'Heal, Divine Protection, Smite', character_class: 'Cleric', stats: {'str' => 15, 'dex' => 20, 'int' => 38})

Quest.create!(name: "The Enigma of the Eclipsed Monolith", description: "A mysterious monolith has suddenly appeared in the heart of the Old Ruins, its dark surface gleaming under the moonlight. The locals whisper of ancient prophecies and arcane knowledge engraved upon its surface. The quest calls for a skilled Mage and a nimble Rogue to investigate the enigma and decipher its hidden secrets, for the fate of the realm may lie within its obsidian core.", requirement: "Mage, Rogue", location: "Old Ruins", reward: 500, user: marnie)
Quest.create!(name: "Sunken Riches: The Underwater Cave", description: "Rumors abound of an underwater cave concealed along the treacherous Coastal Cave. Within its depths rests a fabled treasure lost to the annals of time. The quest beckons the prowess of a skilled Hunter and the unyielding virtue of a noble Paladin to navigate the murky waters, overcome perilous trials, and lay claim to the sunken riches.", requirement: "Hunter, Paladin", location: "Coastal cave", reward: 600, user: david)
Quest.create!(name: "Cursed Forest's Redemption", description: "A malevolent curse shrouds the once lush and vibrant Cursed Forest, transforming it into a haunted realm of darkness and despair. Legend speaks of a powerful Warlock and a devoted Cleric, whose combined magical abilities may dispel the wicked enchantment and restore life to the withering forest. The quest calls upon these chosen heroes to venture into the heart of darkness and bring hope back to the cursed land.", requirement: "Warlock, Cleric", location: "Cursed Forest", reward: 700, user: brian)
Quest.create!(name: "Bloodmoon: Hunt for the Vampire Lord", description: "A reign of terror descends upon the Castle Ruins as a malevolent vampire lord emerges from the shadows, preying upon innocent souls under the blood-red moon. In this dire hour, only a fearsome Barbarian, with unmatched combat prowess, can stand against the creature of the night and bring forth an everlasting dawn to the land.", requirement: "Barbarian", location: "Castle ruins", reward: 400, user: hieu)
Quest.create!(name: "The Princess's Embrace: A Stealthy Rescue Mission", description: "Under the pale moonlight, the princess of the realm has been abducted and imprisoned deep within the treacherous Ogre Cave. This perilous rescue mission demands the finesse of a cunning Mage and the agile skill of a seasoned Rogue to infiltrate the lair, outwit the fearsome ogres, and return the princess to her rightful place.", requirement: "Mage, Rogue", location: "Ogre Cave", reward: 500, user: marnie)
Quest.create!(name: "Spectres of the Haunted Harbor: The Ghost Ship", description: "An ethereal apparition, the Ghost Ship, haunts the mist-laden waters of the Haunted Harbor. Whispered to carry lost souls, the eerie vessel awaits brave souls to unravel its haunting mysteries. The quest seeks the talents of a soulful Bard, whose melodious charm and the dexterity of a skilled Rogue may quell the spirits and guide them towards eternal rest.", requirement: "Bard, Rogue", location: "Haunted Harbor", reward: 800, user: david)
Quest.create!(name: "Jewels of the Desert: Treasure of the Sands", description: "Lost within the endless expanse of the Desert Ruins lies a fabled trove of jewels, guarded by ancient traps and enigmatic riddles. The quest demands the survival instincts of a resilient Warlock and the keen senses of a sharp-eyed Hunter to navigate the treacherous dunes and unlock the secrets of the arid realm.", requirement: "Warlock, Hunter", location: "Desert Ruins", reward: 900, user: brian)
Quest.create!(name: "The Forgotten Temple's Revelation", description: "Concealed amidst the dense foliage of the Jungle Temple, a forgotten realm of mystery awaits those willing to brave its intricate puzzles and tests of faith. The quest seeks the divine guidance of a noble Paladin and the unwavering devotion of a wise Cleric to unveil the temple's ancient secrets and restore its sacred purpose.", requirement: "Paladin, Cleric", location: "Jungle Temple", reward: 1000, user: hieu)
Quest.create!(name: "The Pirate's Plunder", description: "Within the treacherous Pirate Cove, a band of ruthless pirates hoards their ill-gotten treasure. Only a cunning Mage and an alluring Bard, wielding spells and enchanting melodies, can sway the pirates' hearts and minds, unlocking the path to their hidden plunder.", requirement: "Mage, Bard", location: "Pirate Cove", reward: 650, user: marnie)
Quest.create!(name: "Arcane Alchemy: The Wizard's Tower", description: "The Wizard's Tower stands as an enigmatic monument to arcane mastery and magical experimentation. Within its walls, untold mysteries and wonders await those with the wit of a crafty Warlock and the nimble agility of a skilled Rogue. The quest invites these audacious individuals to participate in the wizard's alchemical pursuits and unravel the secrets that lay locked within.", requirement: "Warlock, Rogue", location: "Wizard's Tower", reward: 700, user: david)
Quest.create!(name: "The Enchanted Grove: Guardian of the Forest", description: "Within the Enchanted Grove, a mystical forest said to be protected by ancient spirits, an ominous presence threatens to disrupt the harmony of nature. The quest summons a noble Paladin and a wise Cleric to dispel the darkness and restore the guardian's balance, for the fate of the realm rests upon the sanctuary of the forest.", requirement: "Paladin, Cleric", location: "Enchanted Grove", reward: 750, user: marnie)
Quest.create!(name: "Frozen Destiny: Journey to the Ice Citadel", description: "A mysterious ice citadel, cloaked in eternal frost, has surfaced in the Arctic Wastes. The quest implores a daring Mage and an agile Rogue to navigate the perilous frozen landscape, decipher ancient runes, and unveil the truth behind the citadel's chilling origins.", requirement: "Mage, Rogue", location: "Ice Citadel", reward: 850, user: david)
Quest.create!(name: "The Shifting Sands: A Desert Mirage", description: "The shifting sands of the Mirage Desert conceal a long-lost oasis rumored to hold untold riches and magical wonders. The quest beckons the talents of a resourceful Bard and a sharp-eyed Hunter to survive the ever-changing dunes, decode ancient inscriptions, and unearth the secrets of the ephemeral oasis.", requirement: "Bard, Hunter", location: "Mirage Desert", reward: 950, user: brian)
Quest.create!(name: "Rise of the Dragonheart: The Ancient Volcano", description: "In the heart of the Ancient Volcano, where molten lava flows like a river, a slumbering dragonheart lies dormant. The quest calls upon the courage of a valiant Paladin and the mastery of a skilled Warlock to awaken the ancient spirit and forge a bond between dragon and champion, fated to defend the realm from impending doom.", requirement: "Paladin, Warlock", location: "Ancient Volcano", reward: 1100, user: hieu)
Quest.create!(name: "The Hidden Caverns: Secrets of the Underworld", description: "Hidden beneath the verdant meadows of the Serenity Hills, a labyrinth of ancient caverns conceals forgotten relics of immense power. The quest seeks a Mage and a Rogue, whose combined intellect and agility may navigate the treacherous subterranean maze, uncover the relics, and safeguard them from falling into the wrong hands.", requirement: "Mage, Rogue", location: "Serenity Hills Caverns", reward: 600, user: marnie)
Quest.create!(name: "Harmony's Melody: The Song of the Celestial Harp", description: "A celestial harp, crafted by the gods themselves, is rumored to grant the power to weave harmony and peace across the realm. The quest calls for the artistry of a gifted Bard and the wisdom of a venerable Cleric to resonate with the divine melody, unleash its benevolent force, and orchestrate a symphony of unity.", requirement: "Bard, Cleric", location: "Celestial Grove", reward: 800, user: david)
Quest.create!(name: "The Lost Starlight: Seeking the Astral Comet", description: "A rare astral comet, said to bestow otherworldly knowledge, journeys across the night sky once every thousand years. The quest beckons a Mage and a Hunter, who, under the shimmering constellations, must follow the elusive comet's path, decode the cosmic riddles, and claim the ethereal wisdom.", requirement: "Mage, Hunter", location: "Astral Plains", reward: 950, user: brian)
Quest.create!(name: "Whispers in the Moonlight: The Lunar Enigma", description: "As the moon waxes full, whispers emerge of an enigmatic lunar artifact that holds the power to control the tides of the oceans. The quest summons the presence of a Rogue and a Warlock, who, under the cloak of moonlight, must infiltrate the ancient Lunar Citadel, evade its mysterious guardians, and unlock the secrets of the celestial relic.", requirement: "Rogue, Warlock", location: "Lunar Citadel", reward: 1050, user: hieu)
Quest.create!(name: "The Shadowed Wood: Realm of the Night Elves", description: "Amidst the dense foliage of the Shadowed Wood resides a hidden realm of the reclusive Night Elves, protectors of ancient knowledge. The quest calls upon the skills of a Mage and a Paladin, who, in the embrace of moonlight, must earn the trust of the elusive elves, decipher their age-old scrolls, and preserve the secrets of their mystical domain.", requirement: "Mage, Paladin", location: "Shadowed Wood", reward: 850, user: marnie)
Quest.create!(name: "Eclipse of Eternity: The Astral Observatory", description: "During the rare cosmic event of an eclipse, the Astral Observatory reveals an ancient gateway to other realms. The quest implores a Warlock and a Bard, harnessing the energy of the celestial alignment, to explore the interdimensional gateway, face the trials of astral realms, and bring back the knowledge of the cosmos.", requirement: "Warlock, Bard", location: "Astral Observatory", reward: 1200, user: david)
Quest.create!(name: "The Faerie's Lament: The Crystal Glade", description: "Within the mystical Crystal Glade, a faerie's haunting lament resounds through the forest. The quest calls upon the grace of a Bard and the agility of a Rogue to commune with the sorrowful fae, uncover the source of their grief, and restore the glade's enchanting harmony.", requirement: "Bard, Rogue", location: "Crystal Glade", reward: 800, user: brian)
Quest.create!(name: "Chronicle of the Sages: Library of Ancients", description: "The fabled Library of Ancients, safeguarding knowledge spanning eons, has reemerged from the depths of oblivion. The quest beckons the wisdom of a Cleric and the cunning of a Warlock to delve into the vast tomes, decipher the ancient texts, and unlock the timeless wisdom of the ages.", requirement: "Cleric, Warlock", location: "Library of Ancients", reward: 950, user: hieu)
Quest.create!(name: "Frostfire Dominion: Citadel of the Ice Dragon", description: "Within the impenetrable Citadel of the Ice Dragon, an ancient frostfire elemental awaits liberation. The quest implores the courage of a Paladin and the elemental mastery of a Mage to face the chilling guardians, tame the frostfire, and harness its power for the greater good of the realm.", requirement: "Paladin, Mage", location: "Citadel of the Ice Dragon", reward: 1100, user: marnie)